# Generated by Django 3.1.7 on 2021-04-27 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20210427_1834'),
    ]

    operations = [
        migrations.AddField(
            model_name='knowledge_block',
            name='time_added',
            field=models.DateField(auto_now_add=True, null=True),
        ),
    ]
