# Generated by Django 3.1.7 on 2021-04-27 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_knowledge_block_time_added'),
    ]

    operations = [
        migrations.AlterField(
            model_name='knowledge_block',
            name='time_added',
            field=models.DateField(null=True),
        ),
    ]
