# Generated by Django 3.1.7 on 2021-04-27 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_auto_20210427_1844'),
    ]

    operations = [
        migrations.AlterField(
            model_name='knowledge_block',
            name='time_added',
            field=models.DateTimeField(null=True),
        ),
    ]
