# Generated by Django 3.1.7 on 2021-06-21 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_membership_plan'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='status',
            field=models.CharField(choices=[('public', 'community public'), ('private', 'private')], default='public', max_length=9, null=True),
        ),
    ]
