# Generated by Django 3.1.7 on 2021-04-28 13:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_auto_20210427_2020'),
    ]

    operations = [
        migrations.CreateModel(
            name='category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, null=True)),
                ('icon', models.FileField(upload_to='category_icons/')),
            ],
        ),
        migrations.AlterField(
            model_name='knowledge_block',
            name='content',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='knowledge_block',
            name='time_added',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='lesson',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='lessons', to='main.category'),
        ),
    ]
