# Generated by Django 3.1.7 on 2021-04-28 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_auto_20210428_1335'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='icon',
            field=models.FileField(null=True, upload_to='images/'),
        ),
    ]
