# Generated by Django 3.1.7 on 2021-08-10 13:59

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_auto_20210810_0706'),
    ]

    operations = [
        migrations.AlterField(
            model_name='knowledge_block',
            name='content',
            field=ckeditor.fields.RichTextField(),
        ),
    ]
