# Generated by Django 3.1.7 on 2021-05-21 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_lesson_icon'),
    ]

    operations = [
        migrations.AddField(
            model_name='knowledge_block',
            name='title',
            field=models.CharField(default='new knowledge Block', max_length=100, null=True),
        ),
    ]
