# Generated by Django 3.1.7 on 2021-05-26 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_knowledge_block_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='knowledge_block',
            name='glossary',
            field=models.TextField(null=True),
        ),
    ]
