# Generated by Django 3.1.7 on 2021-08-17 04:27

import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_auto_20210810_1605'),
    ]

    operations = [
        migrations.AlterField(
            model_name='knowledge_block',
            name='audio',
            field=models.FileField(blank=True, null=True, upload_to='audios/'),
        ),
        migrations.AlterField(
            model_name='knowledge_block',
            name='content',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='knowledge_block',
            name='glossary',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='knowledge_block',
            name='resource',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='question',
            name='content',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, default='a question', null=True),
        ),
    ]
