# Generated by Django 3.1.7 on 2021-08-17 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_auto_20210817_0427'),
    ]

    operations = [
        migrations.AlterField(
            model_name='choice',
            name='content',
            field=models.TextField(blank=True, null=True),
        ),
    ]
