# Generated by Django 3.1.7 on 2021-08-24 11:41

from django.db import migrations
import s3_file_field.fields


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_auto_20210817_1308'),
    ]

    operations = [
        migrations.AlterField(
            model_name='knowledge_block',
            name='video',
            field=s3_file_field.fields.S3FileField(),
        ),
    ]
