# Generated by Django 3.1.7 on 2021-08-24 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_auto_20210824_1141'),
    ]

    operations = [
        migrations.AlterField(
            model_name='knowledge_block',
            name='video',
            field=models.FileField(upload_to='videos/'),
        ),
    ]
